#!/usr/bin/env python3
"""Precompute subgoal images for pi0.7 training.

For each subtask boundary, extracts/generates subgoal images:
  - Oracle: actual future frames from the trajectory (fast, no BAGEL)
  - BAGEL: generated by world model (slow, needs GPU)

Only oracle subgoals are required to start training.

Usage:
    # Extract oracle subgoals (fast)
    python scripts/precompute_subgoals.py --data-dir /path/to/dataset

    # Also generate BAGEL subgoals (slow)
    python scripts/precompute_subgoals.py --data-dir /path/to/dataset \
        --bagel-path /path/to/BAGEL-7B-MoT
"""

import argparse
import json
import logging
import os
import random

import av
import numpy as np
from PIL import Image
from tqdm import tqdm

logging.basicConfig(format="%(asctime)s [%(levelname)s] %(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)

CAMERAS = ["observation.images.head", "observation.images.left", "observation.images.right"]
TARGET_SIZE = (448, 448)


def read_frames_batch(video_path: str, frame_indices: list[int]) -> dict[int, Image.Image]:
    """Read multiple frames from AV1 video using PyAV (sequential decode)."""
    frames = {}
    if not frame_indices:
        return frames
    target = set(frame_indices)
    max_idx = max(frame_indices)
    try:
        container = av.open(video_path)
        for i, frame in enumerate(container.decode(video=0)):
            if i in target:
                frames[i] = Image.fromarray(frame.to_ndarray(format="rgb24"))
            if i >= max_idx:
                break
        container.close()
    except Exception as e:
        logger.warning(f"Read failed: {video_path}: {e}")
    return frames


def get_video_path(data_dir: str, ep_idx: int, camera: str) -> str:
    chunk = ep_idx // 1000
    return os.path.join(data_dir, "videos", f"chunk-{chunk:03d}", camera, f"episode_{ep_idx:06d}.mp4")


def process_episode(data_dir: str, ep_idx: int, subtasks: list[dict], cameras: list[str], out_dir: str):
    """Extract oracle subgoal images for one episode."""
    ep_dir = os.path.join(out_dir, f"ep{ep_idx:04d}")
    # Skip if already done
    done_marker = os.path.join(ep_dir, ".done")
    if os.path.exists(done_marker):
        return

    os.makedirs(ep_dir, exist_ok=True)

    for cam in cameras:
        video_path = get_video_path(data_dir, ep_idx, cam)
        if not os.path.exists(video_path):
            continue

        cam_short = cam.split(".")[-1]

        # Collect all frames needed for this camera
        needed = set()
        for st_idx, st in enumerate(subtasks):
            start, end = st["start"], st["end"]
            needed.add(max(0, end - 1))  # oracle end frame
            # Future frames: 25%, 50%, 75% through segment
            dur = end - start
            if dur > 60:
                for frac in [0.25, 0.5, 0.75]:
                    needed.add(start + int(dur * frac))

        # Batch decode
        frames = read_frames_batch(video_path, sorted(needed))

        # Save
        for st_idx, st in enumerate(subtasks):
            start, end = st["start"], st["end"]
            end_idx = max(0, end - 1)

            if end_idx in frames:
                frames[end_idx].resize(TARGET_SIZE).save(
                    os.path.join(ep_dir, f"{cam_short}_st{st_idx}_oracle.png")
                )

            dur = end - start
            if dur > 60:
                for fi, frac in enumerate([0.25, 0.5, 0.75]):
                    fidx = start + int(dur * frac)
                    if fidx in frames:
                        frames[fidx].resize(TARGET_SIZE).save(
                            os.path.join(ep_dir, f"{cam_short}_st{st_idx}_future{fi}.png")
                        )

    # Mark done
    open(done_marker, "w").close()


def generate_bagel_subgoals(data_dir: str, annotations: dict, cameras: list[str],
                             out_dir: str, bagel_path: str, bagel_repo: str | None):
    """Generate BAGEL subgoal images (optional, slow)."""
    from openpi.world_model.bagel_wrapper import BagelWorldModel

    logger.info("Loading BAGEL...")
    model = BagelWorldModel.from_pretrained(bagel_path, bagel_repo=bagel_repo)

    for ep_key, subtasks in tqdm(annotations.items(), desc="BAGEL subgoals"):
        ep_idx = int(ep_key)
        ep_dir = os.path.join(out_dir, f"ep{ep_idx:04d}")
        os.makedirs(ep_dir, exist_ok=True)

        for st_idx, st in enumerate(subtasks):
            # Skip if already generated
            check = os.path.join(ep_dir, f"head_st{st_idx}_bagel.png")
            if os.path.exists(check):
                continue

            # Load start frame for each camera
            obs = {}
            for cam in cameras:
                video_path = get_video_path(data_dir, ep_idx, cam)
                frames = read_frames_batch(video_path, [st["start"]])
                if st["start"] in frames:
                    obs[cam.split(".")[-1]] = frames[st["start"]]

            if not obs:
                continue

            try:
                subgoals = model.generate_subgoals(obs_images=obs, subtask_text=st["text"])
                for view, img in subgoals.items():
                    img.save(os.path.join(ep_dir, f"{view}_st{st_idx}_bagel.png"))
            except Exception as e:
                logger.warning(f"BAGEL failed ep{ep_idx} st{st_idx}: {e}")


def main():
    parser = argparse.ArgumentParser(description="Precompute subgoal images for pi0.7")
    parser.add_argument("--data-dir", type=str, required=True)
    parser.add_argument("--bagel-path", type=str, default=None, help="BAGEL weights path (omit for oracle-only)")
    parser.add_argument("--bagel-repo", type=str, default=None, help="Bagel source code directory")
    parser.add_argument("--cameras", type=str,
                        default="observation.images.head,observation.images.left,observation.images.right")
    args = parser.parse_args()

    ann_path = os.path.join(args.data_dir, "subtask_annotations.json")
    with open(ann_path) as f:
        annotations = json.load(f)
    logger.info(f"{len(annotations)} episodes")

    out_dir = os.path.join(args.data_dir, "subgoal_images")
    cameras = args.cameras.split(",")

    # Oracle subgoals (always)
    logger.info("Extracting oracle subgoals...")
    for ep_key, subtasks in tqdm(annotations.items(), desc="Oracle"):
        process_episode(args.data_dir, int(ep_key), subtasks, cameras, out_dir)

    # BAGEL subgoals (optional)
    if args.bagel_path:
        generate_bagel_subgoals(args.data_dir, annotations, cameras, out_dir,
                                 args.bagel_path, args.bagel_repo)

    logger.info(f"Done. Output: {out_dir}")


if __name__ == "__main__":
    main()
